/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Services.UserService;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrCodeEnum implements TEnum {
  SERVER_ERROR(10001),
  PARAM_ERROR(20001);

  private final int value;

  private ErrCodeEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrCodeEnum findByValue(int value) { 
    switch (value) {
      case 10001:
        return SERVER_ERROR;
      case 20001:
        return PARAM_ERROR;
      default:
        return null;
    }
  }
}
